server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
